# Dependencies
markdown:           kramdown
extensions:         [fenced_code_blocks]
highlighter:        rouge

# Plugins
plugins:               [jekyll-paginate, jekyll-gist, jekyll-compose]

# Permalinks
permalink:          pretty

# Setup
title:              Lambda Sphere
tagline:            'Codito Ergo Sum'
description:        'Software Engineer. This blog serves as a purpose to document some of my steps throughout the lifelong learning journey as well as occasional random musings.'
url:                http://kaunghtet.xyz

author:
  name:             'Kaung Htet Zaw'
  url:              https://twitter.com/khzaw

paginate:           7

# Custom vars
github:             https://github.com/khzaw
twitter:            https://twitter.com/khzaw
email:              me@kaunghtet.xyz
