# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Plugins
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Lambda Sphere
tagline:          'I code. Therefore, I am.'
description:      'Currently pursuing a Computer Science degree here in NUS. This blog serves as a purpose to document some of my steps throughout the lifelong learning journey as well as occasional random stuffs.'
url:              https://khzaw.github.io

author:
  name:           'Kaung Htet Zaw'
  url:            https://twitter.com/khzaw

paginate:         7

# Custom vars
version:          2.0.0

github:           https://github.com/khzaw
twitter:          https://twitter.com/khzaw
email:            emoosx@gmail.com
